### ISSUE TITLE
Призыв

### ISSUE THREAD

**Issue by DeKinci** [NeuroTeam/CyberEden#1]
@JohnKhandygo, я тут описание подвез

**Comment by JohnKhandygo** [comment]
Окей. Звучит норм, осталось определиться, на что конкретно вы собираетесь закоммититься.

**Comment by DeKinci** [comment]
В смысле разделить, кто что делать будет?

**Comment by JohnKhandygo** [comment]
Это мне как раз не важно. Важно понимать, что считать "успешно выполненным заданием". То есть вам сейчас необходимо более менее точно описать функциональность приложения, чтобы а) от вас не требовали сверх этого, б) чтобы я мог определить что формально было сделано, а что нет. Например, количество видов, делаете вы погоду, воду и прочее или нет, обучения нейронная сеть в процессе жизни особи и т.д. Для удобства можно разбить на базовую часть (оценка 3), улучшения базовой версии до оценки 4 и то, что должно быть сделано на 5.

**Comment by DeKinci** [comment]
Цель тут реализовать НС и алгоритм ее обучения, однако мне сложно представить, как его оценить (IQ тест для зайца?). 
Обучение нейронной сети в процессе жизни особи - я пока не представляю, как это сделать, т.к. модель описывает эволюцию, а не развитие отдельной особи. Если подскажете, куда копать - буду благодарен, и симуляция станет намного интереснее.
Формальности, наверное, завтра-послезавтра скажем, сперва надо архитектуру накидать и посмотреть объемы (я с libGDX не работал никогда, и насколько в ней много надо писать понятия не имею)

**Comment by DeKinci** [comment]
>А зачем тогда вообще нужна нейронная сеть, если она никак не обучается?

Она обучается с каждым новым поколением (выживают те, у кого коэффициенты "лучше"). Таблицы вероятностей, во первых, не так интересно, а во вторых, не обладают необходимой гибкостью. Если использовать вероятности, задавая их для каждой возможной взаимной комбинации (трава-вода-заяц-волк), и строя генотип на основе этих вариантов, то вывод получится такой же, как и у НС, но такая система будет обучаться хуже, а особенно "видеть" взаимосвязи между различными условиями. 

Например: если кол-во травы зависит от удаленности от воды, то волкам стоит искать зайцев ближе к воде. В случае НС, где переменные взаимосвязаны и влияют друг на друга, такое поведение возможно, однако в таблице вообще не уверен, что закономерность будет выделена в поведение, так как переменные совершенно ни как не связаны. 

Как вариант, сделать это не сложно (в архитектуру изначально закладываются разные варианты мозгов животных), так что можно попробовать и так, и так.

>Вообще достаточно рискованная затея предлагать вариант задания до оценки его трудоемкости

Вот, оцениваем. Уже даже три интерфейса закоммитил ;)

>как отображать зайцев/волков так, чтобы было понятно, что они генетически похожи или напротив различны

Вариантов несколько:
1. Никак - потому что нет красивого решения этой проблемы.
2. При наведении на клетку показывается инфа о ней (как в игре Factorio), и если там животное, то и о нем тоже - я пока этого варианта придерживаюсь.
3. Как и в жизни, генотип влияет на фенотип (внешний вид животного) - сложно сделать, тк придется генерировать модельку на основе генов, и сделать ее достаточно детализированной, чтобы было видно небольшую разницу. Из вариантов пока только менять оттенки цвета, можно соединить с 2.

>не нужен такой продвинутый движок

Ок. В принципе, пока главное - модель разработать, а с представлением потом разберемся

**Comment by JohnKhandygo** [comment]
Вы каую-то хрень про НС написали. Она у Вас не обучается, Вы будете просто комбинировать (в процессе скрещивания) коэффициенты, никаких "волшебных" закономерностей от этого в новых поколениях не появится. Разве что только случайно. Если Вы не понимаете, что такое НС, то не стоит даже говорить об этом. Придумайте более простой вариант.

Про визуализацию, вариант с цветом мне нравится (чем ближе особи генетически, тем ближе они по цвету). Никаких супер детальных моделей в принципе не надо, плоской графики хватит с избытком. Вплоть до того, что зайцев отображать кружочками, а волков --- квадратиками. 

И я так и не увидел сколь-нибудь формального описания функциональности (а-ля backlog) системы. 

> Вот, оцениваем. Уже даже три интерфейса закоммитил ;)

А второе задание Вы сдавать не собираетесь?

**Comment by DeKinci** [comment]
>Вы каую-то хрень про НС написали.

[Примеры проектов с подобной архитектурой](https://www.youtube.com/results?search_query=neural+network+with+genetic+algorithm)

По такому же запросу можно найти много статей с разным количество математики.

Да, это не НС в ее классическом понимании в плане обучения (не обратное распространение или что-то похожее). 

>Она у Вас не обучается

Не совсем. Генетический алгоритм можно рассматривать как алгоритм эффективного перебора с эвристической оценкой, и в данном случае идет перебор весов в поисках оптимального. Классическими способами обучить НС в данном случае нельзя, потому что нам неизвестны  результаты аппроксимируемой функции, но мы можем сравнить два результата и выбрать тот, который лучше подходит (функцией приспособленности). 

Тем не менее, несмотря на зависимость от случайности, это называется обучением. 

>backlog

Пока все это просто примерное описание. Мы сейчас определяемся с фичами, которые точно бы хотели видеть в проекте.

>А второе задание Вы сдавать не собираетесь?

Неделю назад [сдал](https://github.com/DeKinci/PolyProjects2/tree/master/Myls), открыл [issue](https://github.com/DeKinci/PolyProjects2/issues/3), что прошу следующее, видимо оповещалка не сработала. Там, в принципе, можно упростить некоторые излишние моменты, но можно и не трогать их, имхо не критично.

**Comment by DeKinci** [comment]
Вот, к чему мы пришли:
3: Волки, зайцы, трава, вода (основа)
4: Лето-зима, трава зависит от воды
5: Генерация мира

Вероятно, сделаем больше, но в случае возникновения непредвиденных проблем хотелось бы иметь время на качественное их решение

**Comment by JohnKhandygo** [comment]
В том-то и дело, что сеть в вашем случае --- это просто способ представления алгоритма поведения. Можно взять/придумать любое другое достаточно гибкое представление и работать только с ним. Короче, я понял вашу идею, ни о каком обучении НС речи не идет. 

> Неделю назад сдал, открыл issue, что прошу следующее, видимо оповещалка не сработала. 

А с чего бы ему срабатывать? Вы завели новый репозиторий, но ничего об этом не сообщили.

**Comment by DeKinci** [comment]
>любое другое достаточно гибкое представление и работать только с ним

Зачем, когда есть такой способ?

>Вы завели новый репозиторий

Неа. Новый проект в том же репозитории

**Comment by JohnKhandygo** [comment]
> Зачем, когда есть такой способ?

Для того, чтобы не пороться с реализацией НС. Впрочем, как хотите, дело хозяское.

> Неа. Новый проект в том же репозитории

Тогда странно. Вчера проверил, все ок. Осталось еще Вашему коллеге дозакрыть второе.

**Comment by DeKinci** [comment]
>пороться с реализацией НС

Ради этого (ну и генетики тоже) все и задумывалось. Так интереснее. Наверное, интеллект будет чуть ли не последним, что будет реализовано (относительно 3), так что сможем понять, есть ли время на НС.

**Comment by JohnKhandygo** [comment]
Если там будет тупой интеллек, то задача не тянет на двоих. Изначально речь шла об НС, я готов был заменить это на что-то эквивалентное, но более простое в реализации, однако Вы настояли на НС.

**Comment by DeKinci** [comment]
Не, там будет умный интеллект на НС. Я уже писал такой алгоритм (он опубликован), однако он работал "не очень хорошо", но там я аппроксимировал математические функции (он не особенно предназначен для такого), чтобы разобраться, как это работает

**Comment by JohnKhandygo** [comment]
Окей. Пишите, когда будет что проверять.

**Comment by JohnKhandygo** [comment]
Обоим второе задание зачел, пишите, когда будет что проверять.

**Comment by DeKinci** [comment]
@JohnKhandygo , почти все сделано (для ии осталось одну функцию дописать, сейчас рандомно передвигаются). Можете посмотреть, но за кодстайл и отсутствие многопоточности не ругайте, еще будет рефакторинг.
